[package]
name = "pallet-substratee-registry"
version = "0.6.6-sub2.0.0-alpha.7"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
edition = "2018"

[workspace]
members = [
    'ias-verify',
]

[dependencies]

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.0'

[dependencies.ias-verify]
default-features = false
path = './ias-verify'

[dependencies.sp-std]
default-features = false
version = '2.0.0-alpha.7'

[dependencies.frame-support]
default-features = false
version = '2.0.0-alpha.7'

[dependencies.frame-system]
default-features = false
package = 'frame-system'
version = '2.0.0-alpha.7'

[dependencies.sp-io]
default-features = false
version = '2.0.0-alpha.7'

[dependencies.sp-core]
default-features = false
version = '2.0.0-alpha.7'

[dependencies.timestamp]
default-features = false
package = "pallet-timestamp"
version = "2.0.0-alpha.7"

[dev-dependencies]
hex-literal = "*"
env_logger = "0.7.1"

[dependencies.sp-runtime]
default-features = false
version = '2.0.0-alpha.7'

[dev-dependencies.externalities]
package = "sp-externalities"
version = "0.8.0-alpha.7"

[dev-dependencies.balances]
package = "pallet-balances"
version = '2.0.0-alpha.7'

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'ias-verify/std',
    'sp-std/std',    
    'sp-io/std',
    'sp-core/std',
    'timestamp/std'
]
